/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-12-06 08:26:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<title>注册页面</title>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /> \r\n");
      out.write("<!-- -->\r\n");
      out.write("<script>\r\n");
      out.write("function check(form) {\r\n");
      out.write("            var p1 = form.user_password;\r\n");
      out.write("            var p2 = form.user_password1;\r\n");
      out.write("            if (p1.value != p2.value) {\r\n");
      out.write("                p2.oninvalid();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("        onload = function() {\r\n");
      out.write("            var p2 = document.forms[\"my_f1\"].user_password1;\r\n");
      out.write("            p2.oninvalid = function() {\r\n");
      out.write("                this.setCustomValidity(\"密码不一致，请重新输入\");\r\n");
      out.write("            }\r\n");
      out.write("            p2.oninput = function() {\r\n");
      out.write("                this.setCustomValidity(\"\");\r\n");
      out.write("            }\r\n");
      out.write(" \r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction change(){\r\n");
      out.write("\t\t//切换验证码\r\n");
      out.write("\t\tdocument.getElementById(\"myimg\").src=\"/Edu-ssm/CheckcodeServlet?\"+new Date().getTime();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"\"><span style=\"color: white;font-size:20px;margin-left: 0.4%\">首页</span></a>\r\n");
      out.write("<a href=\"login.html\"><span style=\"color: white;font-size:20px;margin-left: 1%\">登录</span></a>\r\n");
      out.write("<!-- contact-form -->\t\r\n");
      out.write("<div class=\"message warning\">\r\n");
      out.write("<div class=\"inset\">\r\n");
      out.write("\t<div class=\"login-head\">\r\n");
      out.write("\t\t<h1>Regist Form</h1>\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<form action=\"regist.do\" name=\"my_f1\" method=\"post\" onsubmit=\"return check(this);\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"text\" placeholder=\"name\" name=\"user_name\"  autocomplete=\"off\" required>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<input type=\"password\" placeholder=\"password\"  name=\"user_password\" autocomplete=\"off\" required> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<input type=\"password\" placeholder=\"password\"  name=\"user_password1\" autocomplete=\"off\" required> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<input type=\"text\"  class=\"text\" placeholder=\"e_mail\" name=\"user_email\"   autocomplete=\"off\" pattern=\"[^@]+@[^@]+\\.[a-zA-Z]{2,6}\" required>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<input type=\"text\"  placeholder=\"code\"  name=\"checkcode\" autocomplete=\"off\" required=\"required\"> <br>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<img id=\"myimg\"  src=\"/Edu-ssm/CheckcodeServlet\" style=\"cursor:pointer; \" onclick=\"change();\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3 style=\"color:red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"submit\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\"  value=\"Sign in\" >\r\n");
      out.write("\t\t\t\t<h4><a href=\"findUser.jsp\">Lost your Password ?</a></h4>\r\n");
      out.write("\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!--- footer --->\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<p>教育网.@小队</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
