/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-11-26 07:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class teacherShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>教师列表</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<script src=\"http://libs.baidu.com/jquery/2.0.0/jquery.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  <body>\r\n");
      out.write("    <h1>教师列表</h1>\r\n");
      out.write("    \t<ul id=\"list\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    \t</ul>\r\n");
      out.write("  \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t$.post(\"teacher/teacherShow.do\",function(teacherShow){\r\n");
      out.write("    \t\t//console.log(teacherShow);\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tfor(var i=0;i<teacherShow.length;i++){\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tvar teacher = teacherShow[i];\r\n");
      out.write("    \t\t\tvar cName = teacher.cName;\r\n");
      out.write("    \t\t\tvar eName = teacher.eName;\r\n");
      out.write("    \t\t\tvar teacher_image = teacher.teacher_image;\r\n");
      out.write("    \t\t\tvar teacher_info = teacher.teacher_info;\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t$(\"#list\").append(\"<li>\"+cName+\"</li>\");\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+eName+\"</li>\");\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+teacher_image+\"</li>\");\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+teacher_info+\"</li>\");\r\n");
      out.write("    \t\t \t\r\n");
      out.write("\t\t\t\t/* $(\"#list\").append(\"<li>\"+teacherShow[i][\"cName\"]+\"</li>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+teacherShow[i][\"cName\"]+\"</li>\");\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+teacherShow[i][\"eName\"]+\"</li>\");\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+teacherShow[i][\"teacher_image\"]+\"</li>\");\r\n");
      out.write("    \t\t \t$(\"#list\").append(\"<li>\"+teacherShow[i][\"teacher_info\"]+\"</li>\"); */\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("   \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
